### ISSUE TITLE
Will Sapien support WSL in the future?

### ISSUE THREAD

**Issue by ray8828** [haosulab/SAPIEN#102]
Thanks for sharing this great work! I'm wondering is it possible to run sapien on WSL2? if not, is the critical problem the nvidia  driver support for vulkan? or do you have plan for supporting wsl in the future? Thanks!

**Comment by fbxiang** [comment]
Yes, the problem is Nvidia's Vulkan driver. SAPIEN fully supports most native Linux distributions. So the right question is probably whether WSL will support SAPIEN in the future (by supporting Vulkan). If one day they decided to make the driver, SAPIEN will just run.
