### ISSUE TITLE
Unable to make env on server without display. 

### ISSUE THREAD

**Issue by sudhirpratapyadav** [haosulab/SAPIEN#115]
**System:**
 - OS version: 20.04
 - Python version (if applicable): 3.8.13
 - SAPIEN version (pip freeze | grep sapien): sapien==2.2.1
 - Environment: [Desktop / Server with xvfb / Docker with xvfb]: A100 ubuntu server, I don't think it is xvfb

**Describe the bug**
I installed sapein on an A100 server. I ran a docker with ubunut 20.04. Installed sapein and tried to run offscreen example. Got runtime error.
I got following error traceback when executing `python -m sapien.example.offscreen`

```
[2023-02-17 19:46:26.728] [svulkan2] [error] GLFW error: X11: The DISPLAY environment variable is missing
[2023-02-17 19:46:26.728] [svulkan2] [warning] Continue without GLFW.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/sapien/example/offscreen.py", line 41, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/sapien/example/offscreen.py", line 11, in main
    renderer = sapien.SapienRenderer()  # Create a renderer
RuntimeError: Cannot find a suitable rendering device
```

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  Installed sapein via `pip install sapien` 
2. test the offscreen rendering of SAPIEN with the following command `python -m sapien.example.offscreen`

**Expected behavior**
An image will be generated at the current working directory, named output.png.

**Comment by fbxiang** [comment]
Here are the minimal steps I found to enable offscreen rendering.

First, make sure at least `graphics,utility,compute` are added to `NVIDIA_DRIVER_CAPABILITIES` when building the Docker. 
```Dockerfile
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute,display
```
Next, install the `libglvnd-dev` package. (in fact, `libegl1` and `libxext6` should also work) 

Next, you need to make sure both `/usr/share/vulkan/icd.d/nvidia_icd.json` and `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` exist. If not, copy it from the corresponding location on the host machine into the Docker. These files should be provided by the driver, but many servers seem to miss them somehow.

Let me know if this works for you.

**Comment by sudhirpratapyadav** [comment]
Thanks for the reply, I will try the solution and update.

Also I tried to use `fxiangucsd/sapien-build-env` image to create a docker container and when I installed sapien in it using pip it worked. I got output.png when running offline example.

So I guess issue is with adding `graphics` to `NVIDIA_DRIVER_CAPABILITIES`. I will check the above things and then revert back.

Also please add these instructions somewhere in the readme or documentation.

**Comment by fbxiang** [comment]
I am quite surprised that sapien-build-env docker works, as it is not designed to run SAPIEN but for compiling only.

I just figured out the capability thing yesterday, and it is now in the readme on the dev branch. I'll also provide the ICD files with SAPIEN in the next release (as a temporary hack for people with a partial driver installation).

**Comment by sudhirpratapyadav** [comment]
Sorry for my mistake, I rechecked after your comment, image was `fxiangucsd/sapien-rl-env` and not `fxiangucsd/sapien-build-env`.

But yes `fxiangucsd/sapien-rl-env` this image works fine, only thing required is just to install sapien using `pip install sapien`.

**Comment by FeiiYin** [comment]
> Here are the minimal steps I found to enable offscreen rendering.
> 
> First, make sure at least `graphics,utility,compute` are added to `NVIDIA_DRIVER_CAPABILITIES` when building the Docker.
> 
> ```dockerfile
> ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute,display
> ```
> 
> Next, install the `libglvnd-dev` package. (in fact, `libegl1` + `libxext6` should also work)
> 
> Next, you need to make sure both `/usr/share/vulkan/icd.d/nvidia_icd.json` and `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` exist. If not, copy it from the corresponding location on the host machine into the Docker. These files should be provided by the driver, but many servers seem to miss them somehow.
> 
> Let me know if this works for you.

Thx, this works for me. I did not use docker. 
I used `sudo find / -name nvidia_icd.json` to locate and copy the file and used `export` to append the nvidia environment variables.

**Comment by Kimagure7** [comment]
thanks, I did not use docker, this works for me. I created a soft link from /etc/vulkan/icd.d/nvidia_icd.json to /usr/share/icd.d/nvidia_icd.json.

**Comment by geyan21** [comment]
Inspired by @Kimagure7, you can do `export VK_ICD_FILENAMES=/etc/vulkan/icd.d/nvidia_icd.json` if you do not have sudo access to create a link.

**Comment by xiaolijz** [comment]
@geyan21 Hello,I meet a similar question,`[svulkan2][error]Some required Vulkan extension is not present.You may not use the renderer to render`, and I take the method you did but it doesn't work for me. Could you give me some advice, thank you very much, looking forward to your reply.

**Comment by geyan21** [comment]
> @geyan21 Hello,I meet a similar question,`[svulkan2][error]Some required Vulkan extension is not present.You may not use the renderer to render`, and I take the method you did but it doesn't work for me. Could you give me some advice, thank you very much, looking forward to your reply.

Hi @xiaolijz It's probably because the file `nvidia_icd.json` does not exist in the path `/etc/vulkan/icd.d/nvidia_icd.json` in your system. You can simply copy the following file into any path and set it as the environment variable. Hope it helps.
[nvidia_icd.json](https://github.com/user-attachments/files/17442711/nvidia_icd.json)

**Comment by StoneT2000** [comment]
Hi @xiaolijz, @geyan21 is correct, please check the ICD files. 

The more general troubleshooting list you should follow is the following: https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/installation.html#troubleshooting

**Comment by prasuchit** [comment]
@StoneT2000 I just spent the day setting up a cloud desktop with Tesla T4 GPU (which supports Vulkan). I have made sure that Vulkan packages are installed correctly and the ICD files exist at the right location and contain the right contents (as mentioned [here](https://maniskill.readthedocs.io/en/latest/user_guide/getting_started/installation.html#troubleshooting)). I have checked ```nvidia-smi``` and ```nvcc -V``` to make sure everything is set up right.

However, I still see the runtime error ```failed to find a rendering device```. I'm not sure what I'm missing.

I see this thirdparty package using ManiSkill has added a ```--no-render``` option for cloud-based training. Is there something similar I can enable? Would this still work if I'm using end-effector camera image as an input to my policy? I've been stuck on this cloud training problem for a while now. Kindly help.

**Comment by StoneT2000** [comment]
It seems SAPIEN thinks the default cuda device it found cannot render correctly. I recommend uninstalling and reinstalling NVIDIA drivers (nvidia-driver-xxx) and trying again. T4 GPUs should work since google colab works.

@fbxiang the can_render function should be accurate right? We use that in ManiSkill now to help give some early / nicer errors

**Comment by prasuchit** [comment]
Hi,

Thanks for the pointers. I was able to figure out the problem. As mentioned [here](https://github.com/haosulab/SAPIEN/issues/194#issuecomment-2598182640), the system level Vulkan installation was not compatible with the renderer. Installing the Vulkan packages through Conda fixed the problem:

```
conda activate YOUR-ENV-NAME

conda config —add channels conda-forge

conda config —set channel_priority strict

conda install vulkan-tools libvulkan-loader vulkan-volk vulkan-validation-layers
```

After this, I was able to run (via terminal):

```
python


import sapien
my_renderer = sapien.SapienRenderer()
```
And everything worked as expected.
