### ISSUE TITLE
Is there any way to render an actor with transparent background using raytracing?

### ISSUE THREAD

**Issue by adrianxsalazar** [haosulab/SAPIEN#116]
Hi, 

Thank you so much for the SAPIEN simulator; it is a great tool, and I think multiple research projects will benefit other research projects.

I am currently working with the PartNet-Mobility Dataset and using the SAPIEN simulator to render the articulated objects in the dataset. I am rendering the objects using raytracing as the texture quality is much better. However, with this approach, the resulting images have a grey background that I would like to remove. So far, I have removed the grey background using the actor segmentation, but this is far from perfect. I was wondering if you know how to render an object with transparent background using your simulator and raytracing. 

Thank you so much for your time and the SAPIEN simulator.

**Comment by fbxiang** [comment]
I agree it is a good idea to default to `alpha=0` for background. I have made the changes in the dev branch now.
I have also fixed a bug causing the background segmentation to be random.

For now you can just copy everything in the [rt shader folder](https://github.com/haosulab/SAPIEN/tree/dev/vulkan_shader/rt) and set the `camera_shader_dir` accordingly. This shader will be the default in the next release.
