### ISSUE TITLE
ERROR:utils.logger:failed to remove body: invalid body

### ISSUE THREAD

**Issue by boshi-an** [haosulab/SAPIEN#120]
**System:**
 - OS version: Ubuntu 22.04
 - Python version (if applicable): Python 3.8
 - SAPIEN version (pip freeze | grep sapien): 2.2
 - Environment: Desktop

**Describe the bug**
Calling scene.remove_articulation will cause runtime error.

**To Reproduce**
Use render server mode.
`self.scene.remove_articulation(self.obj)` will raise runtime error.

**Expected behavior**
I expected no runtime error.

**Screenshots**
ERROR:utils.logger:failed to remove body: invalid body
Traceback (most recent call last):
  File "/home/boshi/Documents/Science/AdaPose/env/vec_env.py", line 50, in _worker
    env = env_fn()
  File "/home/boshi/Documents/Science/AdaPose/env/sapien_envs/open_cabinet.py", line 159, in __init__
    self.reset()
  File "/home/boshi/Documents/Science/AdaPose/env/sapien_envs/open_cabinet.py", line 544, in reset
    self._change_object()
  File "/home/boshi/Documents/Science/AdaPose/env/sapien_envs/open_cabinet.py", line 260, in _change_object
    self.scene.remove_articulation(self.obj)
RuntimeError: failed to remove body: invalid body

**Additional context**
I read through the C++ code and found the remove_articultion function not implemented.

**Comment by fbxiang** [comment]
Can  you attach your code?
The error  `RuntimeError: failed to remove body: invalid body` should only happen if you pass an object created from a non-render server based implementation to a remove function in a render-server based scene. Or there can be a bug somewhere, so I need the code to reproduce it.

**Comment by boshi-an** [comment]
My part of the code is as below:

```python
self.loader: sapien.URDFLoader = self.scene.create_urdf_loader()
self.loader.fix_root_link = True
self.obj: sapien.Articulation = self.loader.load(object_path)
self.obj.set_root_pose(pose)
self.obj.set_qpos(dof_value)

# Some other work to do

self.scene.remove_articulation(self.obj)
```

**Comment by boshi-an** [comment]
Nice fix!
