### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by boshi-an** [haosulab/SAPIEN#121]
**System:**
 - OS version: Ubuntu22.04
 - SAPIEN version (pip freeze | grep sapien): 2.2.1 or dev

**Describe the bug**
CMake Error at 3rd_party/kuafu/CMakeLists.txt:34 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

**To Reproduce**
```
./docker_build_wheels.sh
```

**Comment by boshi-an** [comment]
not yet, I’m having troubles for other things so did not look into this problemSent from my iPadOn May 15, 2023, at 3:39 AM, Zhenyu Jiang ***@***.***> wrote:﻿
Hi, I got the same error, have you found a fix?

**Comment by lxycopper** [comment]
I got the same error, have you solved it?
