### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by boshi-an** [haosulab/SAPIEN#122]
**System:**
 - OS version: Ubuntu20.04
 - SAPIEN version (pip freeze | grep sapien): dev

**Describe the bug**
/workspace/SAPIEN/src/acd.cpp:49:25: error: ‘Remesh’ is not a member of ‘coacd’; did you mean ‘sapien::Remesh’?
   49 |   auto newMesh = coacd::Remesh(mesh, resolution, level_set);
      |                         ^~~~~~
/workspace/SAPIEN/src/acd.cpp:40:38: note: ‘sapien::Remesh’ declared here
   40 | std::shared_ptr<SConvexMeshGeometry> Remesh(std::shared_ptr<SNonconvexMeshGeometry> g,

**To Reproduce**
./docker_build_wheels.sh

**Comment by fbxiang** [comment]
My guess is that you need to update submodules. Can you try starting over from cloning the repo? And make sure you pull the latest docker as well.
