### ISSUE TITLE
Question regarding PartNet Mobility Dataset

### ISSUE THREAD

**Issue by pushkalkatara** [haosulab/SAPIEN#123]
Hi, I had a question regarding using PartNet Mobility dataset with the Sapiens simulator.

PartNet Mobility dataset provides `mobility.urdf` and `mobility_v2.json` files.

The json contains articulation parameters that are missing in the .urdf file used in sapiens mobility. 

How do I get a mapping of joints in the .urdf to .json file to access all the articulation parameters available in the json?

**Comment by fbxiang** [comment]
I do not think there is much useful information in `mobility_v2.json`. I would consider the json file is really a dirty version of the urdf file.
One exception is the screw joint (e.g. nut-and-bolt like), which is annotated in the json file but not exported to the urdf file. However, both the urdf format and the simulator do not support screw joint, getting this information would also not be that helpful.
