### ISSUE TITLE
Getting RuntimeError: Cannot find a suitable rendering device when runing example after pip installation

### ISSUE THREAD

**Issue by Steve-Tod** [haosulab/SAPIEN#124]
**System:**
 - OS version: [e.g. Ubuntu 16.04]
 - Python version (if applicable): [e.g. Python 3.6]
 - SAPIEN version (pip freeze | grep sapien): 
 - Environment: [Desktop / Server with xvfb / Docker with xvfb]

**Describe the bug**
Getting `RuntimeError: Cannot find a suitable rendering device`

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  `pip install sapien`
2.  `python -m sapien.example.hello_world`

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/haosulab/SAPIEN/assets/26958167/76ad2ed6-55bc-4d31-9ccb-d58a93a2f2b4)

**Comment by Steve-Tod** [comment]
![image](https://github.com/haosulab/SAPIEN/assets/26958167/b2357b05-e6d7-4650-94ec-0a077a42355d)

**Comment by hantao-zhou** [comment]
Have you solved it? Met the same problem here

**Comment by Steve-Tod** [comment]
No, I haven't and gave up 😂
