### ISSUE TITLE
Problem for examples/basic/physics.py

### ISSUE THREAD

**Issue by Boey-li** [haosulab/SAPIEN#128]
Hello, thanks for the amazing work! I am trying the examples you provided. However, for the examples/basic/physics.py, I used the default setting to run the render but the box/sphere can not slide down the slope within 10,000 steps. I am wondering whether there exists some bugs on this example? Or is there anything I need to take care of to reproduce the results? 

Thanks for taking time on this matter!

**Comment by YongLD** [comment]
I have the same problem, Have you fix this?

**Comment by YongLD** [comment]
I have found the problem: the 'pause' are initialized as ‘True’, so you must press c to start --.--
