### ISSUE TITLE
The sapien examples cannot work

### ISSUE THREAD

**Issue by lxycopper** [haosulab/SAPIEN#132]
**System:**
 - OS version: Ubuntu 20.04
 - Python version (if applicable): Python 3.8
 - SAPIEN version: 2.2.2
 - Environment: Server with xvfb

After 'pip install sapien' to install the package, 
1) when I type in '$ python -m sapien.example.offscreen' in terminal, it shows:
![image](https://github.com/haosulab/SAPIEN/assets/52530394/a61cc59d-1675-45a9-b712-c6020f8cc55d)

2) when I type in '$ python -m sapien.example.hello_world' in terminal, it shows:
![image](https://github.com/haosulab/SAPIEN/assets/52530394/522d13e7-244d-45b9-9fc8-afaa13992c03)

**Comment by elenacliu** [comment]
I'm not sure, it seems like a problem with your X11 environment setting? Do you want to show the gui?

**Comment by lxycopper** [comment]
> I'm not sure, it seems like a problem with your X11 environment setting? Do you want to show the gui?

I use a display. The command '$ python -m sapien.example.offscreen' works for me. However, the command '$ python -m sapien.example.hello_world' shows a new bug as below:
![image](https://github.com/haosulab/SAPIEN/assets/52530394/f2183734-af75-4170-9c33-047ffe7d93b0)

**Comment by lxycopper** [comment]
> > I'm not sure, it seems like a problem with your X11 environment setting? Do you want to show the gui?
> 
> I use a display. The command '$ python -m sapien.example.offscreen' works for me. However, the command '$ python -m sapien.example.hello_world' shows a new bug as below: ![image](https://user-images.githubusercontent.com/52530394/263900000-f2183734-af75-4170-9c33-047ffe7d93b0.png)
By connecting a display physically rather than remote desktop connection, my problem has been solved
