### ISSUE TITLE
pip install sapien failed

### ISSUE THREAD

**Issue by gyj155** [haosulab/SAPIEN#140]
**System:**
 - OS version: macos Sonoma 14.0
 - Python version (if applicable): Python3.8
 - SAPIEN version (pip freeze | grep sapien): /
 - Environment: [Desktop / Server with xvfb / Docker with xvfb]

When I enter the command 'pip install sapien' in the terminal, it shows 'ERROR: Could not find a version that satisfies the requirement sapien (from versions: none). ERROR: No matching distribution found for sapien.' Are there any other methods to resolve this issue or to skip this step

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  
2. 
<img width="565" alt="截屏2023-10-22 14 21 53" src="https://github.com/haosulab/SAPIEN/assets/66156334/c542117b-dc54-44b7-9650-d76a7f0303d9">

**Expected behavior**
install successfully

**Comment by fly0520** [comment]
I've met the same situation....

**Comment by fly0520** [comment]
You need to use python3.7, even python3.8 does not work

**Comment by fbxiang** [comment]
Currently we do not have plans to continue macOS support. We will mainly focusing on development on Linux, and we are evaluating how hard it is to support Windows. I recommend switching to Linux if you want to use the latest features.

**Comment by gyj155** [comment]
Thank you.
