### ISSUE TITLE
RuntimeError: failed to find a rendering device

### ISSUE THREAD

**Issue by SparKgod1** [haosulab/SAPIEN#164]
I run in ubuntu20.04 run on vmware workstation pro17

`
File "/home/spark/miniconda3/envs/dexycb/lib/python3.8/site-packages/sapien/wrapper/scene.py", line 25, in __init__
    [sapien.physx.PhysxCpuSystem(), sapien.render.RenderSystem()]
RuntimeError: failed to find a rendering device
`
Why this error occurs,appreciate for your advice,thanks.

**Comment by jzy1412** [comment]
I also encountered this error. The key point is that when I set it up on a server two weeks ago, I didn't have this problem, but now I'm experiencing it when setting up a new server.

**Comment by SparKgod1** [comment]
I switched from using virtual machine to a dual-boot system and no longer encounter errors, hoping this can help you.

**Comment by SparKgod1** [comment]
> I also encountered this error. The key point is that when I set it up on a server two weeks ago, I didn't have this problem, but now I'm experiencing it when setting up a new server.

Perhaps your server lacks the necessary hardware capabilities to perform the rendering.
