### ISSUE TITLE
Question about the function camera.get_normal_rgba() in past version

### ISSUE THREAD

**Issue by isabella4444x** [haosulab/SAPIEN#166]
Hi,
I want to use SAPIEN 3.0 version ,and find function camera.**get_normal_rgba()** which is used in 0.8 Version disappeared.
[https://github.com/TritiumR/Where2Explore/blob/656f3a470ddc18885980aadd1ab316414fc3c90a/code/camera.py#L78]
And I can't find the documention for 0.8 version .
So do you know is there any similar method ?
Thanks a lot!

**Comment by StoneT2000** [comment]
@fbxiang

**Comment by fbxiang** [comment]
The method should be `get_picture("Normal")` assuming the shader you are using has the "Normal" texture. The default one should be fine.
