### ISSUE TITLE
Difference between link.get_id() in the past 0.8 version and link.get_index() in 3.0 version

### ISSUE THREAD

**Issue by isabella4444x** [haosulab/SAPIEN#167]
Hello,
I 'm confused about the `camera.get_picture("Segmentation") `,    [the API doc ](https://sapien-sim.github.io/docs/user_guide/rendering/camera.html#visualize-segmentation) said the `camera.get_picture("Segmentation") [...,1]` indicates acotr/link id label while `[..., 0] ` indicates visual label.

I wonder whether the [...,1] label means each pixel 's link id in this picture? 
But the values I get from picture   seem to be discrete numbers? For example, 1, 8 ,9 but no 0,2,3....
How can I get the same link id  as past?

In past 0.8 version, only one get_segmentation() and indicates the link id  as [https://github.com/TritiumR/Where2Explore/blob/656f3a470ddc18885980aadd1ab316414fc3c90a/code/camera.py#L87](https://github.com/TritiumR/Where2Explore/blob/656f3a470ddc18885980aadd1ab316414fc3c90a/code/camera.py#L87)

I also want to know what I can get from picture ? As the example in API doc, `get_picture('Color'),('Segmentation'),('Position')`?
And what else is available?

Thanks a lot!!!

**Comment by fbxiang** [comment]
[..., 1] does mean each pixel's link id in the segmentation picture. In SAPIEN 2, they correspond to `link.get_id()` or SAPIEN 3's `entity.per_scene_id`.  Some links do not have visuals, so they do not appear in the image.

SAPIEN 2 uses a fully configurable shader system and the names of the textures are specified in the shader files. For example, when using the default shader, the image names are declared in the fragment shader (with prefix `out` removed)
https://github.com/haosulab/SAPIEN/blob/master/vulkan_shader/ibl/composite0.frag#L20-L26
https://github.com/haosulab/SAPIEN/blob/master/vulkan_shader/ibl/deferred.frag#L69

**Comment by fbxiang** [comment]
The `link.get_index` function gets the link index in its articulation. i.e. `articulation.links[link.get_index()]` will return the link. per_scene_id is a more general concept that is unique per entity in each scene.

**Comment by isabella4444x** [comment]
Thank you !
I have used the entity.get_global_id() to replace now!
