### ISSUE TITLE
Question About the TODO : render_id_to_visual_name() in scene

### ISSUE THREAD

**Issue by isabella4444x** [haosulab/SAPIEN#169]
Hi,
I find the property ` render_id_to_visual_name()` in class `Scene()` shows TODO.
And I wonder if there is any way to correspond the link's visual name with the link ? Such as I want to find the handle of a kettle ,with the name 'link 1' and visual name 'xxx handle ' in urdf?But seemly the link can only get name but not the visual name like the **'handle'**?
Thank you a lot!

**Comment by fbxiang** [comment]
This function is not crucial for SAPIEN 3. It is there because it was a function from SAPIEN 2 and we might be able to improve backward compatibility. You can access the per-scene-id for render shapes from `sapien.render.RenderShape.get_per_scene_id()`. For example you can try the following code.
```python
    for body in scene.render_system.render_bodies:
        for shape in body.render_shapes:
            print(shape.name, shape.get_per_scene_id())
```
