### ISSUE TITLE
No Vulkan extensions found for window surface creation and libGLX_nvidia.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by andyoung009** [haosulab/SAPIEN#172]
**System:**
 - OS version: [e.g. Ubuntu 20.04]
 - Python version (if applicable): [e.g. Python 3.10]
 - SAPIEN version (pip freeze | grep sapien): sapien==2.2.2
 - Environment: [Desktop]

**Describe the bug**
When I try to run `python -m sapien.example.hello_world`, the error comes as followling:
```
Traceback (most recent call last):
  File "/home/axe/miniconda3/envs/centergrasp_env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/axe/miniconda3/envs/centergrasp_env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/axe/miniconda3/envs/centergrasp_env/lib/python3.10/site-packages/sapien/example/hello_world.py", line 56, in <module>
    main()
  File "/home/axe/miniconda3/envs/centergrasp_env/lib/python3.10/site-packages/sapien/example/hello_world.py", line 19, in main
    renderer = sapien.SapienRenderer()  # Create a renderer
RuntimeError: createInstance: No Vulkan extensions found for window surface creation (hint: set VK_ICD_FILENAMES to `locate icd.json`).
```

**Screenshots**

![image](https://github.com/user-attachments/assets/5c72ffb1-b18b-41d5-911f-421cd0788562)

**Additional context**
Is there a problem with my nvidia driver installation？ The system also cannot find the libGLX_nvidia.so.0 file. Is there any other solution besides downgrading and reinstalling the nvidia driver? I am worried that it will bring other system-related package problems. My computer configuration is ubuntu20.04, NVIDIA GeForce RTX 4070. The nvidia Driver Version is 550.76 while the cuda version is 11.8.
I use locate icd.json to find the icd.json, receive that in terminal.
```
/etc/vulkan/icd.d/nvidia_icd.json
/home/axe/miniconda3/envs/lerobot/lib/python3.10/site-packages/sapien/vulkan_library/nvidia_icd.json
/usr/share/code/vk_swiftshader_icd.json
```
I use sudo apt install libvulkan1 libvulkan-dev to install the vulkan driver, use vulkaninfo to get some detail info of Vulkan, but all these did not solve the problem. There may be some useful infomation in [here](https://github.com/robot-learning-freiburg/CenterGrasp/issues/2).
Thanks for your help!

**Comment by andyoung009** [comment]
Hi, I just reinstalled the Nvidia driver then reslove this issue.

**Comment by Mr-Neurotic** [comment]
Hi, I've also encountered this problem. So, is your solution just to reinstall the NVIDIA driver?

**Comment by andyoung009** [comment]
> Hi, I've also encountered this problem. So, is your solution just to reinstall the NVIDIA driver?

Yes!
