### ISSUE TITLE
The camera should be able to be mounted on more types of parents, not just ActorBase.

### ISSUE THREAD

**Issue by fffffq99** [haosulab/SAPIEN#175]
_**Is your feature request related to a problem? Please describe. ** 
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I mounted a camera on my real robotic arm, and now I want to add it to the simulation, but it failed.

_**Describe the solution you'd like**
A clear and concise description of what you want to happen._
    Just like the title. I want to mount the camera on ```Linkbase```, but I'm not sure if there's already a way to do it. If so, please forgive me for disturbing.

_**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered._
   Set the camera with ```set_pose()``` at each step.

**Comment by fbxiang** [comment]
Based on your description, it seems you are on an early version of SAPIEN. in SAPIEN 3, the core of SAPIEN has been completely overhauled and adopts an ECS architecture. In SAPIEN 3, a camera is a component that can be mounted to any entity. In fact, physical actors and links are also simply components and any component can be combined with a camera. You can find the new documentation at https://sapien-sim.github.io/docs/

I suggest switching to SAPIEN 3 (3.0.0b1 on pypi). This version will probably be released as a stable release soon.

**Comment by fffffq99** [comment]
Thank you for your reply. I used `pip install sapien` to install it, and the version is 2.2. Now I will try using the `3.0.0b1` version you suggested. This issue can be closed. Thank you.
