### ISSUE TITLE
How to visualize an actor by vertices?

### ISSUE THREAD

**Issue by bb0928** [haosulab/SAPIEN#183]
Thanks for your excellent work.
However, I want to visualize an actor based on vertices rather than sapien.pose (i.e. transl+quat), and I can't find relevant tutorial on docs.
Could you please offer any help about this? Many thanks.

**Comment by bb0928** [comment]
i think i have solved this issue. Thanks.

**Comment by chengfengpiao** [comment]
Could you please explain how you achieve this? Are there any insights you can share?

**Comment by bb0928** [comment]
you can refer to a github repo named 'dex-retargeting', which visualized a deformable object (mano hand) by vertices rather than setting pose. However, objects are no longer actors as long as you render them by vertices.
