### ISSUE TITLE
Does Sapien provide an interface for computing Forward Kinematics?

### ISSUE THREAD

**Issue by yilin404** [haosulab/SAPIEN#185]
I hope this message finds you well.
I am currently working with Sapien for robotic simulations, and I am interested in calculating the forward kinematics (FK) of a robotic arm within the environment. However, I couldn't find any direct reference in the documentation regarding an interface for performing FK calculations.
Could you kindly confirm whether Sapien provides a built-in interface or method to compute forward kinematics? If such functionality exists, would you be able to share any relevant documentation or example code to help me integrate this into my project?
Thank you very much for your time and assistance. I look forward to your response.

**Comment by fbxiang** [comment]
First, forward kinematics is always part of the simulator and `articulation.set_qpos(qpos)` has already computed FK and  `link.pose` now contains the result. For example, you can create 2 scenes and use one for computing IK.
However, if solving FK using the simulator sounds like cheating or maybe you want higher accuracy, SAPIEN bundles with Pinocchio. You can compute FK by.
```
model = articulation.create_pinocchio_model()
model.compute_forward_kinematics(qpos)
model.get_link_pose(link_index)
```

**Comment by yilin404** [comment]
Thank you for your response! The issue has been resolved, and I will go ahead and close this issue. If anything else comes up, I’ll reach out. Thanks again for your help!
