### ISSUE TITLE
Is there an API to retrieve information about all obstacles in the environment and build a grid/voxel map?

### ISSUE THREAD

**Issue by yilin404** [haosulab/SAPIEN#187]
I hope this message finds you well.
I am currently working on a mobile robotic arm task using the Sapien framework. As part of this project, I need to retrieve information about all obstacles present in the environment to build a map for path planning and collision avoidance. Specifically, I am looking for an API or method that allows me to gather details about all obstacles in the simulation and construct either a grid map or voxel-based map to represent the environment.
Could you kindly confirm if such an API exists in Sapien? If so, I would appreciate any documentation, code examples, or guidance on how to use it to obtain the necessary information and build the map.
Thank you for your time and assistance. I look forward to your response.

**Comment by fbxiang** [comment]
SAPIEN can allow you to extract the collision meshes of everything in the scene. This has been done in ManiSkill to extract the bounding box of everything here 
https://github.com/haosulab/ManiSkill/blob/be920fde669856c4267409a3c333c0ebb81af131/mani_skill/utils/geometry/geometry.py#L73-L104
Building voxel map is a different problem and you will need to find a geometry processing library such as trimesh to do the mesh to voxel conversion.

**Comment by yilin404** [comment]
Thank you so much for your valuable input! I really appreciate the time and effort you put into suggesting this approach. I will definitely give it a try and let you know how it goes. Thanks again for your help!
