### ISSUE TITLE
error w.r.t vulkan

### ISSUE THREAD

**Issue by TwiceMao** [haosulab/SAPIEN#188]
**System:**
 - OS version: [Ubuntu 18.04]
 - Python version (if applicable): [e.g. Python 3.9]
 - SAPIEN version (pip freeze 2.2.2 ): 
 - Environment: [Server with xvfb ]
NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7 
ii  libvulkan-dev:amd64                        1.1.70+dfsg1-1ubuntu0.18.04.1                   amd64        Vulkan loader library -- development files
ii  libvulkan1:amd64                           1.1.70+dfsg1-1ubuntu0.18.04.1                   amd64        Vulkan loader library
ii  mesa-vulkan-drivers:amd64                  20.0.8-0ubuntu1~18.04.1                         amd64        Mesa Vulkan graphics drivers
ii  vulkan-utils                               1.1.70+dfsg1-1ubuntu0.18.04.1                   amd64        Miscellaneous Vulkan utilities

**Describe the bug**

RuntimeError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed
when run code:
`        if self._renderer_type == "sapien":
            self._renderer = sapien.SapienRenderer(**renderer_kwargs)`

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  
2. 

**Expected behavior**
No runtime error

**Screenshots**

**Additional context**

**Comment by fbxiang** [comment]
The only thing I can see from this error is that the GPU driver is not configured correctly, and it is hard to diagnose the exact cause, but I do see a few potential issues.
First, the server seems quite outdated, as Ubuntu 18.04 is eol at the moment and Nvidia driver 515 is also quite old. You also mentioned that you are using Xvfb, and I remember xvfb back in the days do not play well with GPUs. While these do not necessarily cause issues, it suggests that your setup is quite old, and old servers also have a tendency to not install Nvidia drivers correctly. For example, it is very common to only install the compute capabilities without graphics capabilities, which are used by Vulkan. I also suggest upgrading SAPIEN to 3.0b1 or whatever is used in ManiSkill as we have more workarounds for misconfigured servers, but it is unlikely to directly work in your case.
I suggest upgrading the system if possible. If not, you can try to run Vulkan test programs such as vulkaninfo and vkcube (which needs a desktop environment or xvfb). If those simple programs cannot run, you can seek help from the Vulkan community as they know a lot more about debugging graphics issues.
