### ISSUE TITLE
[Question] What's the difference between `root_pose` and `root_link.pose` ?

### ISSUE THREAD

**Issue by yilin404** [haosulab/SAPIEN#189]
I use such code to create a actor and get its `root_pose` and `root_link.pose`:
```
self.lever_door, self.lever_door_data = create_urdf_obj(
            self.scene, 
            sapien.Pose(p=[3, 3, 0], q=t3d.euler.euler2quat(0, 0, 0)), 
            modelname="005_lever_door",
            fix_root_link=True,
            model_id=0,)
        
print(self.lever_door.root_pose)
print(self.lever_door.pose)
print(self.lever_door.find_link_by_name("link_0").pose)
print(self.lever_door.find_link_by_name("link_0").get_pose())
```
And the result is:
<img width="247" alt="image" src="https://github.com/user-attachments/assets/d2105769-6881-4f4e-976d-daf96eff510e" />
I want to know why they are different? And what is `root_pose` mean in SAPIEN?

**Comment by StoneT2000** [comment]
They should be the exact same. in fact root pose references root link pose.

**Comment by yilin404** [comment]
Thank you for your reply! After further investigation, I realized the issue was with my own code. I apologize for the inconvenience caused. I appreciate your help and patience, and I'll make sure to check my code more thoroughly in the future. Thanks again!
