### ISSUE TITLE
Segmentation Fault when initializing with Vulkan

### ISSUE THREAD

**Issue by Leeeshuz** [haosulab/SAPIEN#34]
I have been trapped in the vulkan environment setting for days. After I install `sapien` via `pip install sapien` and try to run the `hello_world.py`, it shows `vk::PhysicalDevice::getSurfaceFormatsKHR: ErrorInitializationFailed`. 

I think the problem may be related to the `vulkan`, so I tried to install vulkan dependencies via `apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils` and run the comand `vulkaninfo`. Getting the segmentation fault error as follows:

```

(sapien) root@node146246:~# vulkaninfo
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

















Instance Extensions:
====================
Instance Extensions     count = 15
        VK_KHR_device_group_creation        : extension revision  1
        VK_KHR_display                      : extension revision 23
        VK_KHR_external_fence_capabilities  : extension revision  1
        VK_KHR_external_memory_capabilities : extension revision  1
        VK_KHR_external_semaphore_capabilities: extension revision  1
        VK_KHR_get_physical_device_properties2: extension revision  2
        VK_KHR_get_surface_capabilities2    : extension revision  1
        VK_KHR_surface                      : extension revision 25
        VK_KHR_xcb_surface                  : extension revision  6
        VK_KHR_xlib_surface                 : extension revision  6
        VK_EXT_acquire_xlib_display         : extension revision  1
        VK_EXT_debug_report                 : extension revision  9
        VK_EXT_debug_utils                  : extension revision  2
        VK_EXT_direct_mode_display          : extension revision  1
        VK_EXT_display_surface_counter      : extension revision  1
Layers: count = 3
=======
VK_LAYER_NV_optimus (NVIDIA Optimus layer) Vulkan version 1.2.168, layer version 1
        Layer Extensions        count = 0
        Devices         count = 8
                GPU id       : 0 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 1 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 2 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 3 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 4 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 5 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 6 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 7 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0

VK_LAYER_NV_optimus (NVIDIA Optimus layer) Vulkan version 1.2.168, layer version 1
        Layer Extensions        count = 0
        Devices         count = 8
                GPU id       : 0 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 1 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 2 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 3 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 4 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 5 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 6 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 7 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0

VK_LAYER_LUNARG_standard_validation (LunarG Standard Validation Layer) Vulkan version 1.0.70, layer version 1
        Layer Extensions        count = 0
        Devices         count = 8
                GPU id       : 0 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 1 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 2 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 3 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 4 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 5 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 6 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0
                GPU id       : 7 (NVIDIA TITAN Xp)
                Layer-Device Extensions count = 0

Presentable Surfaces:
=====================
GPU id       : 0 (NVIDIA TITAN Xp)
Surface type : VK_KHR_xcb_surface
Formats:                count = 0
Present Modes:          count = 3
        FIFO_KHR
        FIFO_RELAXED_KHR
        IMMEDIATE_KHR
Segmentation fault (core dumped)

```

The project was running on a headless remote server with Ubuntu18.04 and has 8 Titan Xp GPUs. I tried to install VNC for desktop visualization however nothing changed. Anybody can help me with the environment setting? What should I do to correctly setup the vulkan environment? Too little information about this on the Internet. Thanks a lot!

**Comment by fbxiang** [comment]
The first thing you should try is setting the environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` (make sure the file exists). If other issues happen with present surfaces, you can then disable display. visualization is very hard to set up on a remote server and there are specific VNC parameters required. I recommend not doing visualization remotely.

**Comment by Leeeshuz** [comment]
> The first thing you should try is setting the environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` (make sure the file exists). If other issues happen with present surfaces, you can then disable display. visualization is very hard to set up on a remote server and there are specific VNC parameters required. I recommend not doing visualization remotely.

The errors mentioned above are all with the `VK_ICD_FILENAMES` set. However, the `nvidia_icd.json` was not located as said, while it was located in somewhere like `/etc/.../vulkan`, dont know why. Maybe it is related to some other robot simulation environment I installed before, such as habitat or ai2thor. Also installing 'mesa-vulkan-drivers' only gives the icd files related to intel or radeon without nvidia_icd, which is very strange.

Does it related to the GL support provided by the nvidia driver and how to check/make sure all the basic environments/libraries are correct before installing sapien? This is really hard for me since I am new to this area.

**Comment by fbxiang** [comment]
Do you mean the VK_ICD_FILENAMES resolves the issue? That would be great.
In fact, Vulkan has nothing to do with GL, but Vulkan and Opengl are packaged together when installing Nvidia drivers. The ICD file is just telling the program which driver library to use.
The good thing about SAPIEN is that it comes with all dependencies packaged, including Vulkan. The only things you need to ensure are
1. NVIDIA driver (AMD could probably also work but we have not done much testing), since we cannot ship that...
2. VK_ICD_FILENAMES since we cannot predict if you are using NVIDIA or AMD card.

**Comment by Leeeshuz** [comment]
No. What I mean is I have already set the right VK_ICD_FILENAMES while the errors still exist. So do you mean that there is no need to install libraries like `libvulkan1, vulkan-utils, mesa-vulkan-drivers` via apt-get? Just `pip install sapien` with the ICD file set would be fine? If so, I will try more times.

**Comment by fbxiang** [comment]
Yes. I have been using the following Docker environment for SAPIEN (offscreen only). There is no need to install the Vulkan libraries (the reason why some people resolve the issue with mesa-vulkan-drivers is that it writes the ICD file). 
```Dockerfile
FROM nvidia/cudagl:11.0-devel-ubuntu20.04
RUN apt update && apt upgrade -y
RUN mkdir -p /usr/share/vulkan/icd.d
RUN echo '{"file_format_version": "1.0.0", "ICD": {"library_path": "libGLX_nvidia.so.0", "api_version": "1.1.84"}}' > /usr/share/vulkan/icd.d/nvidia_icd.json
RUN apt install -y python3 python3-pip
RUN pip3 install sapien transforms3d
````
