### ISSUE TITLE
Failed to cook mesh

### ISSUE THREAD

**Issue by sxy7147** [haosulab/SAPIEN#37]
**System:**
 - OS version: Ubuntu 18.04
 - Python version (if applicable): 3.6.13
 - SAPIEN version (pip freeze | grep sapien): 0.8.0
 - Environment: Ubuntu Desktop

**Describe the bug**
I have downloaded the full PartNet-Mobility dataset, but it reports errors when I try to load some particular objects, such as TrashCan with id 102259, 103012, and 102244. See the screenshot.

**Screenshots**
<img width="1010" alt="sapien_error" src="https://user-images.githubusercontent.com/52743903/135269393-a6bd434b-33ee-4de2-8abc-22c3529eadea.png">

**Comment by fbxiang** [comment]
It seems you are using a very outdated version of SAPIEN. Please date to the latest version. It probably will not fix the errors since some models in the dataset are indeed not correctly modeled, but SAPIEN should correctly ignore these cases.
