### ISSUE TITLE
Explicitly close a scene in the engine

### ISSUE THREAD

**Issue by ZhangHanbo** [haosulab/SAPIEN#39]
In my project, it is required that the simulator could reset the environment for many times.

I found that there might be two ways to achieve so:

1) clear all objects, or called actors.
2) delete the scene and re-initialize it. In my case, I just assign a none value to it.

However, for 1), I found that it will throw out an exception. For 2), the memory occupied will increase gradually and the running speed for each initialization will also be slower and slower.

Is there anyway to explicitly and completely delete the scene in an engine?

**Comment by ZhangHanbo** [comment]
> I see. For the last Mac version, your described issues are all occurring. Please try to use Linux version for now. We will fix most reported Linux version issues immediately while it is very hard to maintain a Mac release right now.
> Let me know if similar issues occur on the latest Linux release.

It works perfectly on Linux. Thanks!

BTW, do you have any further plan for the more detailed documents? Currently, the documents seem quite basic.

**Comment by fbxiang** [comment]
The current documentation is what we believe will be used by most people. The features not documented are things we believe are either not mature enough to tell everybody or very rarely used. 
We are working on auto-generating an API doc page. It will provide exactly the same information as what a Python IDE can provide (by parsing the pyi doc, which ultimately is generated from the `pysapien_content.hpp` file), but I can see many people prefer reading them online.

**Comment by fbxiang** [comment]
The doc is available starting from version 2.0.
