### ISSUE TITLE
Is there a easy way to get 2D pixel position of a 3D point?

### ISSUE THREAD

**Issue by ChicyChen** [haosulab/SAPIEN#44]
Sorry to trouble again!
I try to obtain the 2D pixel position of a 3D point after projection of a perspective camera.
What confuses me is the extrinsic matrix and coordinates. How can I get the camera extrinsic parameters from the camera pose I use for `camera_mount_actor.set_pose` and the `pose` feature in `camera = scene.add_mounted_camera`?
I tried to use `get_model_matrix`, `get_projection_matrix`, but I still don't understand what the two matrix means...

**Comment by ChicyChen** [comment]
What does w mean?
Besides, while we set:
```
box0 = create_box(
            scene,
            sapien.Pose(p = position),
            half_size = [0.1, 0.1, 0.1],
            color = [0., 1., 0.], #green
            name = 'box',
        )
```
which coordinate space should we use for `position`, world, mount, or camera?
Thank you!

**Comment by fbxiang** [comment]
w is the 4th coordinate, our coordinates are `(x,y,z,w)` using homogeneous coordinates representations.

SAPIEN does not have a create_box function so I am not sure what you are talking about. My best guess would be that this code will create a box centered at its origin and then place it at the given pose. If so, the pose passed in would be the pose of the box in world, i.e. the transformation from box space to world space. `position` is just 3 numbers representing the translation part of this transformation.

**Comment by fbxiang** [comment]
Yes, it should be in world frame. To check that, you can take a look at `actor.pose`. This pose is in world frame.
I cannot tell what can go wrong without seeing your code or your camera placement. Can you provide the camera matrices? To me, `im_pos0` does not look right based on your picture.

**Comment by ChicyChen** [comment]
camera.get_model_matrix()
```
[[ 0.          0.         -1.         -0.9452107 ]
 [-1.          0.          0.         -0.03047524]
 [ 0.          1.          0.          0.8906712 ]
 [ 0.          0.          0.          1.        ]]
```
camera.get_projection_matrix()
```
[[ 1.8058456e+00 -0.0000000e+00  3.8582087e-04  0.0000000e+00]
 [ 0.0000000e+00 -2.4177437e+00  5.1653385e-04  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -1.0000100e+00 -1.0000100e-02]
 [ 0.0000000e+00  0.0000000e+00 -1.0000000e+00  0.0000000e+00]]
```
position:
`[0.22000028 -0.17195201 -0.19]`
im_pos0:
```
[[ 0.14147677]
 [-1.08067119]
 [-1.16521098]
 [ 1.        ]]
```
im_pos1:
```
[[0.25503564]
 [2.61218407]
 [1.15522254]
 [1.16521098]]
```
im_pos2:
```
[[0.21887507]
 [2.24181211]
 [0.99142779]
 [1.        ]]
```
image:
<img width="618" alt="Screen Shot 2021-10-22 at 00 35 30" src="https://user-images.githubusercontent.com/48748560/138394050-acd25990-4eba-4869-b289-0a5e3ecf1ccf.png">

**Comment by fbxiang** [comment]
Since there are no updates and the sapien renderer computes matrices correctly, issue closed.
