### ISSUE TITLE
How to move end-effector to handle?

### ISSUE THREAD

**Issue by arjung128** [haosulab/SAPIEN#47]
I downloaded a drawer (`sapien_assets_id = 41083`) and am using a panda robot. How can I move the end-effector to the handle of the drawer? Currently, I am guessing and checking both the pose of the end-effector with the `self.move_to_pose(pose, with_screw)` function, as well as the pose of the drawer, which as you can imagine is very slow and tedious.

I'm not entirely sure how to get the handle location: `asset.get_joints()[-2].get_pose_in_child()` gives me `Pose([0, 0, 0], [0.707107, 0, -0.707107, 0])` while `asset.get_joints()[-2].get_child_link().pose` gives me `Pose([0, 1.86265e-09, 0], [1, 0, 0, 0])`; why are these two different? Additionally, both of these values don't seem to update even after I try setting the pose with `asset.set_pose(sapien.Pose([1.0155, 0.25, -0.1]))` -- is this because these values are relative to the root pose?

**Comment by arjung128** [comment]
I'm sorry for not using the issue template. I didn't think my question fit under either bug report or feature request, but I understand that it is important to follow protocol. I will try using it from now onwards.

When I mentioned to `self.move_to_pose()`, I was referring to the `move_to_pose_with_RRTConnect()` function provided in the [motion planning tutorial](https://sapien.ucsd.edu/docs/latest/tutorial/motion_planning/plan_a_path.html). As I said in my original post, I have been trying to find a pose of the end-effector such that the the handle of the drawer can be grasped, and I have been trying to do this by simply guessing and checking various end-effector poses -- I have gotten close to the handle, but not exactly the right pose, so I have not been able to grasp the handle and open the drawer.

How can I get the visual body of the handle and extract the mesh? Once I have this, I think your suggestion is I can find out the 3D coordinate of the handle relative to the root pose and then use this to determine the end-effector pose for grasping, correct? 

Could this be done in another way? I was wondering if I could use one of the provided successful demonstrations to obtain the optimal grasping pose, and then use move_to_pose_with_RRTConnect to move the end-effector to this pose. But for this to work, I would need all of the information about the environment that was used in the demonstration to replicate the environment (locations and poses of objects and robot) -- is this available?

Thank you for the clarification about the distinction between pose_in_child and link.pose. I really appreciate your help and your prompt replies.

**Comment by fbxiang** [comment]
An example of finding the visual mesh is used in the ManiSkill repo here, 
https://github.com/haosulab/ManiSkill/blob/main/mani_skill/env/open_cabinet_door_drawer.py#L79-L83

I am not sure what demonstrations you are talking about, if it is ManiSkill, then the only way to find the handle is to use the segmentation since the simulation shapes will not be available at test time. The provided trajectories also do not necessarily use the handle, so I am not sure how you will approach it.

I believe the full environment can be recovered from demonstration states, but you should ask ManiSkill people to be sure.

**Comment by arjung128** [comment]
Thank you for the pointer, this is very helpful!
