### ISSUE TITLE
Incompatible function arguments in 'camera.py'

### ISSUE THREAD

**Issue by Berk035** [haosulab/SAPIEN#48]
**System:**
 - OS version: Ubuntu 18.04
 - Python version (if applicable): 3.8.12
 - SAPIEN version (pip freeze | grep sapien): 1.1.1
 - Environment: Desktop

**Describe the bug**
I am just began to study on SAPIEN. I couldn't run the script _camera.py_ in examples. I changed the URDF path and implemented the file. Unfortunately, I got incompatible function error. Do

**To Reproduce**
My environment packages is:
`(sapien) berk@berk-HP:~/VS_Project/SAPIEN$ conda list
packages in environment at /home/berk/anaconda3/envs/sapien:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
anyio                     3.3.4                    pypi_0    pypi
argon2-cffi               21.1.0                   pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    4.1.0                    pypi_0    pypi
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py38h06a4308_0  
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1                    pypi_0    pypi
decorator                 5.1.0                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
idna                      3.3                      pypi_0    pypi
ipykernel                 6.4.2                    pypi_0    pypi
ipython                   7.29.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.5                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    3.0.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
json5                     0.9.6                    pypi_0    pypi
jsonschema                4.1.2                    pypi_0    pypi
jupyter-client            7.0.6                    pypi_0    pypi
jupyter-core              4.9.1                    pypi_0    pypi
jupyter-packaging         0.11.0                   pypi_0    pypi
jupyter-server            1.11.1                   pypi_0    pypi
jupyterlab                3.2.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.8.2                    pypi_0    pypi
jupyterlab-widgets        1.0.2                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libedit                   3.1.20210714         h7f8727e_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
nbclassic                 0.3.4                    pypi_0    pypi
nbclient                  0.5.4                    pypi_0    pypi
nbconvert                 6.2.0                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1                    pypi_0    pypi
notebook                  6.4.5                    pypi_0    pypi
numpy                     1.21.3                   pypi_0    pypi
open3d                    0.13.0                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.2                     pypi_0    pypi
pandas                    1.3.4                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0  
prometheus-client         0.12.0                   pypi_0    pypi
prompt-toolkit            3.0.21                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.10.0                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
python                    3.8.12               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.26.0                   pypi_0    pypi
requests-unixsocket       0.2.0                    pypi_0    pypi
sapien                    1.1.1                    pypi_0    pypi
scikit-learn              1.0.1                    pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
terminado                 0.12.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
tomlkit                   0.7.2                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
transforms3d              0.3.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.7                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.2.1                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
widgetsnbextension        3.5.2                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  `

**Screenshots**
![image](https://user-images.githubusercontent.com/44226026/139524685-2cd9d8e1-b7be-4533-86f6-49629e92f990.png)

Can you suggest a solution?

Thank you in advance.

**Comment by fbxiang** [comment]
You just need to add `fovx=0` (if you read the error, the only thing missing is fovx). Can you show where you find the example? This code is meant for sapien >= 2.0. The argument becomes optional after 2.0.

**Comment by fbxiang** [comment]
Actually I see, this repo is already in the 2.0 version. So this is expected behavior, and you need to install the 2.0a version or compile from source. Otherwise, you should stick with examples in the documentation of the corresponding version here.
https://sapien.ucsd.edu/docs/1.1/index.html

**Comment by Berk035** [comment]
Thank you for your response @fbxiang . I tried rebuild the environment with fork and clone repository. Unfortunately, the building was unsuccessful from the source. I followed the steps:

> Make sure all submodules are initialized git submodule update --init --recursive

Result:

> Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:jetd1/kuafu.git' into submodule path '/home/berk/VS_Project/SAPIEN/3rd_party/kuafu' failed
Failed to clone '3rd_party/kuafu'. Retry scheduled
Cloning into '/home/berk/VS_Project/SAPIEN/3rd_party/pybind11'...
Cloning into '/home/berk/VS_Project/SAPIEN/3rd_party/sapien-vulkan-2'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
###################
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:haosulab/sapien-vulkan-2.git' into submodule path '/home/berk/VS_Project/SAPIEN/3rd_party/sapien-vulkan-2' failed
Failed to clone '3rd_party/sapien-vulkan-2'. Retry scheduled
Cloning into '/home/berk/VS_Project/SAPIEN/3rd_party/tinyxml2'...
Cloning into '/home/berk/VS_Project/SAPIEN/3rd_party/kuafu'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
###################
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:jetd1/kuafu.git' into submodule path '/home/berk/VS_Project/SAPIEN/3rd_party/kuafu' failed
Failed to clone '3rd_party/kuafu' a second time, aborting`

Then, I tried `python setup.py bdist_wheel` . Result:

> Traceback (most recent call last):
  File "setup.py", line 142, in <module>
    version=check_version_info()[3],
  File "setup.py", line 107, in check_version_info
    with open("python/VERSION") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'python/VERSION'

Another try with `./build.sh` Result:

> invalid version

I think the git version is up to date. My sapien package is also Latest version (1.1.1).  I couldn't solve the problem.. If you have another suggestion, I will try immediately. Thanks.

**Comment by fbxiang** [comment]
Several submodules are specified with ssh for easier development. So you will need to setup ssh access for your github account.
Next, as we have stated in the readme, it is very tricky to build outside of docker, so we only support build with docker. The version file should be generated when you run the docker build scripts.
