### ISSUE TITLE
vkCore: Missing physical device extension: VK_KHR_pipeline_library

### ISSUE THREAD

**Issue by XYZ-99** [haosulab/SAPIEN#51]
## System:

 - OS version: Ubuntu 18.04
 - Python version (if applicable): Python 3.8.12
 - SAPIEN version (pip freeze | grep sapien): 2.0a0
 - Environment: Desktop

## Describe the bug

```
engine = sapien.Engine()
render_config = sapien.KuafuConfig()
render_config.use_viewer = False
render_config.spp = 32
render_config.max_bounces = 8
render_config.use_denoiser = True
renderer = sapien.KuafuRenderer(render_config)
```
gives:
```
INFO - 2021-11-04 13:30:47,535 - topics - topicmanager initialized
[2021-11-04 13:30:47.674] [kuafu] [info] Camera is not yet usable due to uninitialized context!
[2021-11-04 13:30:47.674] [kuafu] [info] Offscreen mode enabled.
[2021-11-04 13:30:47.674] [kuafu] [warning] Denoiser ON! You must have an NVIDIA GPU with driver version > 470 installed.
vkCore: Missing physical device extension: VK_KHR_pipeline_library
[1]    11190 segmentation fault (core dumped)  python ./renderer/sapien_render.py
```

## Expected behavior

The exact same code could run on another desktop with the same vulkan-related packges installed:

```
$ apt list --installed | grep vulkan

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvulkan-dev/bionic,now 1.2.189.0~rc1-1lunarg18.04-1 amd64 [installed,automatic]
libvulkan1/bionic,now 1.2.189.0~rc1-1lunarg18.04-1 amd64 [installed]
lunarg-vulkan-layers/bionic,now 1.2.189.0~rc2-1lunarg18.04-1 amd64 [installed,automatic]
mesa-vulkan-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
vulkan-extensionlayer/bionic,now 1.2.189.0~rc1-1lunarg18.04-1 amd64 [installed,automatic]
vulkan-headers/bionic,bionic,now 1.2.189.0~rc1-1lunarg18.04-1 all [installed,automatic]
vulkan-sdk/bionic,bionic,now 1.2.189.0~rc2-1lunarg18.04-1 all [installed]
vulkan-tools/bionic,now 1.2.189.0~rc2-1lunarg18.04-1 amd64 [installed,automatic]
vulkan-validationlayers/bionic,now 1.2.189.0~rc2-1lunarg18.04-1 amd64 [installed,automatic]
vulkan-validationlayers-dev/bionic,now 1.2.189.0~rc2-1lunarg18.04-1 amd64 [installed,automatic]
```

The only noted difference is that the NVIDIA driver version for the functioning desktop is 470.xx while the version for the failed desktop is 495.44 (which is updated as it suggests that we have driver version > 470, see the terminal output above). Nevertheless, this difference should not lead to problems with vulkan.

**Comment by fbxiang** [comment]
Can you first go to the sapien installation path, `XXXX/site-packages/sapien/core` and try `ldd pysapien.cpython-38-x86_64-linux-gnu.so | grep vulkan` to make sure vulkan is indeed version 1.2.189 just in case there are multiple versions on your system?

**Comment by XYZ-99** [comment]
The output to `ldd pysapien.cpython-38-x86_64-linux-gnu.so | grep vulkan` is
```
libvulkan.so.1 => /usr/lib/x86_64-linux-gnu/libvulkan.so.1 (0x00007fc979a91000)
```
and under `/usr/lib/x86_64-linux-gnu`,
```
:/usr/lib/x86_64-linux-gnu % ll *vulkan*
lrwxrwxrwx 1 root root   35  3 21:41 libnvidia-vulkan-producer.so -> libnvidia-vulkan-producer.so.495.44
-rwxr-xr-x 1 root root  19K  3 21:41 libnvidia-vulkan-producer.so.495.44
-rw-r--r-- 1 root root 7.9M  12  2020 libvulkan_intel.so
-rw-r--r-- 1 root root 6.1M  12  2020 libvulkan_radeon.so
lrwxrwxrwx 1 root root   14  28 05:58 libvulkan.so -> libvulkan.so.1
lrwxrwxrwx 1 root root   20  28 05:58 libvulkan.so.1 -> libvulkan.so.1.2.189
-rw-r--r-- 1 root root 331K  28 05:58 libvulkan.so.1.2.189
```
so yes, I only have version 1.2.189. FYI, the functioning desktop produces the same result.

Do you have any further idea?

**Comment by fbxiang** [comment]
Have you set environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`? The Vulkan version seems fine. And what is your GPU? (it should work for any RTX GPU)

**Comment by XYZ-99** [comment]
I have set the `VK_ICD_FILENAMES` while still unable to run the code, and strangely enough, the functioning desktop does not even set this variable.

My GPU is GeForce GTX 1650, and the functioning desktop is GeForce GTX 3090. Could this be the culprit?

**Comment by fbxiang** [comment]
It is possible. We have only tested on RTX GPUs (which are optimized for ray tracing) and if you look closely, 3090 is RTX instead of GTX. My guess would be that Nvidia did not implement this extension for Linux drivers with GTX GPU.

**Comment by XYZ-99** [comment]
That's so depressing... But your timely response definitely made my day! Thank you :)
