### ISSUE TITLE
Some questions about the setting of model mass

### ISSUE THREAD

**Issue by poisonwine** [haosulab/SAPIEN#52]
I have some questions about the setting of the model mass:
1. If I  load a model and don't set its mass, how the mass be calculated in the SAPIEN simulator? The density of the model is fixed?
2. if I want to change the distribution of the model mass, can I only set mass value and ignore other parameters such as the mass center of the model?  How should I change the mass centers of models with different shapes and sizes?

**Comment by fbxiang** [comment]
1. You can set the density when adding collision shapes density is a parameter. When loading urdf, the density is a property on the loader.
2. You can simply set the mass properties. If you know the mass distribution, simply call [actor.set_mass_and_inertia](https://github.com/haosulab/SAPIEN/blob/master/python/pysapien_content.hpp#L1445-L1464)

**Comment by poisonwine** [comment]
Thanks a lot. By the way, if the scene has more than two objects, can I get the contact information of a specific object? ( such as other object ids)

**Comment by fbxiang** [comment]
`scene.get_contacts` will give all the contacts. Then you can find all the properties of the contacts, including the actors in contact.

**Comment by poisonwine** [comment]
> `scene.get_contacts` will give all the contacts. Then you can find all the properties of the contacts, including the actors in contact.

OK, I'll try that. Thanks
