### ISSUE TITLE
vkCore: Missing physical device extension: VK_KHR_synchronization2

### ISSUE THREAD

**Issue by chengyzhao** [haosulab/SAPIEN#55]
**System:**
 - OS version: Ubuntu 18.04
 - Python version (if applicable): Python 3.8.10
 - SAPIEN version (pip freeze | grep sapien): 2.0a0
 - Environment: Desktop, with GPU GeForce RTX 3060

**Describe the bug**
```
config = sapien.KuafuConfig()
# config.spp = 64
# config.use_denoiser = True
renderer = sapien.KuafuRenderer(config)
```
gives
```
[2021-12-13 16:14:36.042] [kuafu] [info] Camera is not yet usable due to uninitialized context!
[2021-12-13 16:14:36.042] [kuafu] [info] Offscreen mode enabled.
vkCore: Missing physical device extension: VK_KHR_synchronization2
[1] 28289 segmentation fault (core dumped)  python render.py
```

**Expected behavior**
I would use Kuafu ray tracing to render RGB image, but it seems to be something wrong. I've check #51 to check my vulkan setting, and the result is the only version of vulkan I have is version 1.2.189. Even though I set the environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`, it still comes the same error.

**Additional context**
I think maybe there's something wrong with my NVIDIA driver version? The version on my desktop is 460.91.03, which is <470. I'm not sure if I have to use the NVIDIA driver version >470 even if I won't use the denoiser?

**Comment by fbxiang** [comment]
Maybe you can try `vulkaninfo` or `vulkaninfo --html` (for better readability) to see if vulkan has picked up the correct library and gpu with the environment variables set. 

If so, you can try `vulkaninfo | grep synchronization2` to see if it is supported by the driver. If not, updating the driver will work.

**Comment by chengyzhao** [comment]
Sorry for the late reply. I've tried `vulkaninfo --html` and it gives

![Snipaste_2021-12-16_17-15-27](https://user-images.githubusercontent.com/69140506/146358168-7e026fc5-294e-477f-afeb-bc84530e2d79.jpg)

And when I ran `vulkaninfo | grep synchronization2`, it gives
```
VK_LAYER_KHRONOS_synchronization2 (Khronos Synchronization2 layer) Vulkan version 1.2.189, layer version 1: VK_KHR_synchronization2 : extension revision 1
```
I'm not sure whether it is well set. Is there something wrong with the driver or the environment variables?

**Comment by fbxiang** [comment]
It appears at least it should not be missing this extension. I would first check if you have multiple versions of vulkan libraries and SAPIEN picked up an incorrect one. You can do that by finding the sapien .so file in the installation directory (site-packages for your python) and use `ldd` to see the linked Vulkan library location. Or maybe you can just upgrade the driver anyway since it might just resolve the issue, and it is in general a good idea to upgrade drivers.

**Comment by chengyzhao** [comment]
Sorry for the late reply. I've solve this problem by changing to another Desktop. Thanks for your help!
