### ISSUE TITLE
Identifying points in .obj file

### ISSUE THREAD

**Issue by arjung128** [haosulab/SAPIEN#61]
**Is your feature request related to a problem? Please describe.**
I would like to use the visualizer to identify points on objects and then get the closest vertex in the .obj file. Is this currently possible?

If I want to do this for getting the corner point of a cabinet, this is tedious: I would have to identify the cabinet part which contains the point I'm interested in, and then find the point in that file. I can identify the corner based on some kind of heuristic, e.g. smallest x and y coordinate. However, if I want to do this for a point which is not a corner but rather on the middle of a surface, I don't know how I can do this. 

**Describe the solution you'd like**
If I can click on a point on the object in the visualizer and get the closest vertex in the .obj file, that would be great.

**Describe alternatives you've considered**
Perhaps I can use some other .obj visualizer to do this, but I'm not sure whether this feature is supported in any other library. Do you know of any such library?

**Additional context**
N/A

**Comment by fbxiang** [comment]
This feature already exists in the renderer, by [default](https://github.com/haosulab/SAPIEN/blob/6bc3f4e2be910199b793f185aea5791d9f193e4c/vulkan_shader/ibl/gbuffer.frag#L47), the .obj coordinate is rendered to a custom texture (this is implemented to demonstrate how custom texture can be added to the renderer, but it seems like it is exactly what you need). The texture can be accessed by camera.get_float_texture("Custom") or window.get_float_texture("Custom").
This feature seems too specific to be added to the viewer itself, but the viewer is all in python so you can modify it to provide the custom texture value when you click on a pixel.
