### ISSUE TITLE
Convert robot qpos to robot joint positions

### ISSUE THREAD

**Issue by arjung128** [haosulab/SAPIEN#62]
**Is your feature request related to a problem? Please describe.**
Is there an easy way to get the robot's joint positions given the robot's qpos (i.e. the robot state from [here](https://github.com/haosulab/ManiSkill/wiki/Detailed-Explanation-of-The-Agent-State-Vector))?

**Describe the solution you'd like**
A function which converts the robot qpos to the robot's joint positions.

**Describe alternatives you've considered**
I'm sure there is a way to manually calculate this, but I'm not sure how exactly to do this / if there are any libraries which could be used.

**Additional context**
N/A

**Comment by fbxiang** [comment]
What you need is called the forward kinematics. Many libraries are able to do it. In sapien, we have integrated the pinocchio library to compute this without changing the simulation state. You can do
```python
model = articulation.create_pinocchio_model()
model.compute_forward_kinematics(qpos)
link_pose = model.get_link_pose(link_idx) # link idx is the index of the link in articulation.get_links()
# Then if you need the joint pose instead, you can do
joint_pose = link_pose * joint.get_pose_in_child()  # assuming the link is the child of the joint
```
Alternatively, you can also find plenty of libraries to support forward kinematics with URDF input.

**Comment by arjung128** [comment]
I see, thanks!

What is the type of articulation? I tried:

```
loader: sapien.URDFLoader = scene.create_urdf_loader()
robot: sapien.Articulation = loader.load("./assets/robot/panda/panda.urdf")
model = robot.create_pinocchio_model()
```

Here, robot is of type `sapien.core.pysapien.Articulation` but this does not seem to have an attribute `create_pinocchio_model`.

Also, what is the type of `joint`?

**Comment by fbxiang** [comment]
The `create_pinocchio_model` function is defined on sapien.core.pysapien.Articulation [here](https://github.com/haosulab/SAPIEN/blob/6bc3f4e2be910199b793f185aea5791d9f193e4c/python/pysapien_content.hpp#L1162). Are you using the latest version?
joint is returned by `articulation.get_joints()`

**Comment by arjung128** [comment]
That fixed it, thanks!
