### ISSUE TITLE
How to render images in headless mode? 

### ISSUE THREAD

**Issue by CodeLHY** [haosulab/SAPIEN#72]
I am using SAPIEN to render images in our remote server, however, when I ran the helloword.py the following error corrupt:
[2022-03-29 13:21:22.988] [svulkan2] [error] GLFW error: X11: Failed to open display :0.0
[2022-03-29 13:21:22.989] [svulkan2] [warning] Continue without GLFW.
[2022-03-29 13:21:23.014] [svulkan2] [error] Some required Vulkan extension is not present. You may not use the renderer to render, however, CPU resources will be still available.
Segmentation fault (core dumped)

It seems because of that there is no display connected to our remote server.  How can I run SAPIEN in headless mode?

**Comment by fbxiang** [comment]
I believe currently the Kuafu renderer only provides rgba image rendering. So everything you have are as expected. So for now, you can only use the ray tracing for rendering rgba. If you need things like segmentation and position, you can stick to the original rasterization renderer.

**Comment by CodeLHY** [comment]
When will the kuafu's position rendering be public?

**Comment by fbxiang** [comment]
Kuafu probably will not provide position rendering any time soon, as it would be much faster to use rasterization for position rendering. The aim of Kuafu is to render photorealistic images instead of rendering multiple modalities.

**Comment by CodeLHY** [comment]
Then how can I get the results of "simulation of active stereovision depth sensors" as described in the paper: "Close the Visual Domain Gap byPhysics-Grounded Active StereovisionDepth Sensor Simulation"

**Comment by fbxiang** [comment]
This paper is based on stereovision instead of directly rendering position. You can refer to our documentation here.
https://sapien.ucsd.edu/docs/2.0/tutorial/rendering/raytracing_renderer.html#sensor-simulation-in-kuafu

**Comment by CodeLHY** [comment]
Yes, you are right, I'm sorry for my mistake, this work is really amazing!
