### ISSUE TITLE
PartNet-Mobility Dataset Collision Issue

### ISSUE THREAD

**Issue by harryzhangOG** [haosulab/SAPIEN#73]
**System:**
 - OS version: Ubuntu 20.04
 - Python version (if applicable): Python 3.8
 - SAPIEN version (pip freeze | grep sapien): 1.1.1
 - Environment: Desktop

**Describe the bug**
When I load objects such as Ovens and Microwaves into a pybullet environment and place a cube inside those objects, there will be weird mesh collision issue: 1. the cube might penetrate the wall 2. the cube might be shot out by the partnet-mobility object. See the two gifs below.
![cube_fail](https://user-images.githubusercontent.com/43732483/161401592-9e87d5af-587f-41d8-9129-94c618045515.gif)
![cube_fail](https://user-images.githubusercontent.com/43732483/161401611-4f722422-2653-4665-a6b6-004a7b39a1f3.gif)

**To Reproduce**
Steps to reproduce the behavior (use pastebin for code):
1.  Load any Oven/Microwave into pybullet
2.  Create a cube with proper xyz location and start stepping.

**Expected behavior**
Weird physics.

**Screenshots**

**Additional context**

**Comment by fbxiang** [comment]
This Github repo is for the SAPIEN simulator.
You should probably examine the collision shapes generated by bullet and report any unexpected simulation behavior to them.

**Comment by fbxiang** [comment]
I can now provide a guess for this issue. Bullet is probably taking the convex hull of the collision shapes, and you can use their v-hacd module to do a decomposition. Please refer to their documentation for details.
