### ISSUE TITLE
ray tracing meets bug in GTX1050

### ISSUE THREAD

**Issue by Haian-Jin** [haosulab/SAPIEN#74]
When I run the code named kuafu.py provided by the Sapien toturial, I met the same bug mentioned in #51 on my laptop but everything worked fine on my Linux server. The major difference is that my laptop's GPU is GTX1050 while my linux server has several RTX2080Ti.
So I think there may be some bugs for Sapien's ray tracing on non-RTX GPU.
![image](https://user-images.githubusercontent.com/79512936/162349981-58041a93-b941-451d-9139-799ac8865dec.png)
The return message is "vkCore: Missing physical device extension: VK_KHR_pipeline_library", which is the same as #51

**Comment by fbxiang** [comment]
I believe this issue indeed exists by according to reports. However, there is not much we can do since it looks like this required extension is not provided by the Nvidia driver for non RTX GPU.

**Comment by Haian-Jin** [comment]
> I believe this issue indeed exists according to many reports. However, there is not much we can do since it looks like this required extension is not provided by the Nvidia driver for non RTX GPU.

Thanks for your reply
