### ISSUE TITLE
Question about scaling URDF

### ISSUE THREAD

**Issue by WangYixuan12** [haosulab/SAPIEN#83]
Thank you for your great work in building this environment! I am trying to load URDF from Partnet-mobility dataset. However, I found that some objects' scales can be too large. I change the scale by manually changing the number in URDF file. However, this is not scalable. I am wondering whether there are some other ways to solve this problem.

**Comment by fbxiang** [comment]
The URDF loader in SAPIEN has a scale field. You can use it to scale the objects.

**Comment by WangYixuan12** [comment]
Got it. Thanks!
