### ISSUE TITLE
change resolution of ActiveLightSensor

### ISSUE THREAD

**Issue by crtie** [haosulab/SAPIEN#84]
Hello! I'm using ActiveLightSensor in my project. But I discover the default resolution of ActiveLightSensor(1920*1080) is so high that it's slow to get pointcloud, so I want to decrease the resolution. So I operate like this.
![图片](https://user-images.githubusercontent.com/61133940/183339651-9145fcf9-d14e-45e6-8723-08121d7eb42a.png)
But it reports a "malloc():invalid size (unsorted)" error.
Is my operation wrong? What't the right method to change ActiveLightSensor's resolution?
my sapien version is 2.1.0
Thanks!

**Comment by jetd1** [comment]
Hi, ActiveLightSensor currently creates all required buffers during initialization. It will break if you change the camera parameters afterwards. In your case we recommend dropping `sensor_type='fakesense_j415'` and passing all camera parameters manually when creating the sensor. See https://github.com/haosulab/SAPIEN/blob/02287b2a2ebdce5f38f637577f6debe4fbb757ce/python/py_package/sensor/activelight.py#L188 for the actual parameters for 'fakesense_j415'.
