### ISSUE TITLE
Can nvidia A100 GPU support vulkan?

### ISSUE THREAD

**Issue by JYChen18** [haosulab/SAPIEN#85]
I want to run some sapien codes (which needs vulkan) in a server where I don't have either sudo privilege or an installed vulkan package. Docker is also not supported due to some reason. Is there any way I can make it? Can I install vulkan in anaconda?

**Comment by fbxiang** [comment]
The first thing you can try is to install Vulkan-SDK from https://vulkan.lunarg.com/sdk/home and run their setup script (no root privilege required).
If Vulkan-SDK does not work, then your GPU driver probably does not support Vulkan.

**Comment by JYChen18** [comment]
I test the installed Vulkan-SDF by `vkvia` and `vulkaninfo`, and the error goes as below:
`VIA_ERROR:   Vulkan failed to find a compatible driver.
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /vulkan-sdk/1.3.216.0/source/Vulkan-Tools/vulkaninfo/vulkaninfo.h:665:vkCreateInstance failed with 
ERROR_INCOMPATIBLE_DRIVER`

Is it the problem of hardware or the software? Can I fix this issue if I can use docker?

**Comment by fbxiang** [comment]
It is hard to tell without trying. Is `nvidia-smi` giving you proper output? If so, you can try Docker to see if it works. If not, Docker probably will not help.

**Comment by JYChen18** [comment]
`nvidia-smi` can give me the proper output when the `vulkaninfo` reports the above error, both on the host and in Docker.

**Comment by JYChen18** [comment]
This is the output of `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   27C    P0    62W / 400W |      0MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by JYChen18** [comment]
Finally find that the problem has nothing to do with A100 and is related to the version of the Nvidia driver. After updating the driver from 470.57.02 to 510.47.03, the problem was solved.

**Comment by jiiiijiij** [comment]
I saw on a video on linus channel, it appear to not support vulkan
