### ISSUE TITLE
Grasping a 3D Object Tightly

### ISSUE THREAD

**Issue by jerrykeung666** [haosulab/SAPIEN#87]
**Is your feature request related to a problem? Please describe.**
Hi, is there a way to make the gripper grasp the 3D object tightly?

**Describe the solution you'd like**
The gripper can grasp the object tightly when the object rotates a certain degree. I think all what I need is to increase both the gripper's and the 3D object surface's friction.

**Describe alternatives you've considered**
I thought it had something to do with the friction, and have added physical material for the 3D object, with dynamic_friction & static_friction & restitution equal to 1e5, but still failed.

**Additional context**
Please see the attached video.

https://user-images.githubusercontent.com/77949159/189551904-bf2be8bf-bedb-4b8f-a478-a9a13f224b91.mp4

**Comment by fbxiang** [comment]
First, the restitution is a value between 0 and 1, with 0 producing the most stable contact.
Next, friction has the best results when you set them to a normal value (around 0-2). Unrealistic value may cause issues in simulation. The most stable behavior is actually achieved when you match the real scenario.
From your video, I would guess you either have a big time step, or the robot gripper is executing unrealistically large forces. The first thing you can try is to set the time step to 1/500. You may also want to increase the solver iterations (5 should enough but you can use 20 if you want to rule out this possibility).
I hope this is enough to solve your issue.

**Comment by jerrykeung666** [comment]
It helps! Thanks!
