### ISSUE TITLE
Segmentation Fault: vkCore: Local Vulkan SDK API version is outdated

### ISSUE THREAD

**Issue by akshaygadipatil** [haosulab/SAPIEN#90]
Installed sapien2.0 using docker file. 

I can import the core library, but when I try to call KuafuRenderer, i get an error that says: `vkCore: Local Vulkan SDK API version is outdated.
Segmentation fault (core dumped)`

Attaching a screenshot below. 

@fbxiang any pointers to fix this issue? Thanks.

![Screen Shot 2022-09-20 at 2 55 44 PM](https://user-images.githubusercontent.com/22264995/191371900-4c20cae3-a13b-4141-823f-7c0c370b1e24.png)

**Comment by fbxiang** [comment]
It sounds like your graphics driver is outdated. However, I do not have enough information to say anything. (You would want to fill out the issue template, especially the system section)
Moreover, can you provide the output of `vulkaninfo`? It is probably provided by the package `vulkan-utils`.

**Comment by akshaygadipatil** [comment]
Resolved. The problem was with `libvulkan` version (1.1.70 as opposed to the required 1.2.189).

**Comment by sky23249** [comment]
> Resolved. The problem was with `libvulkan` version (1.1.70 as opposed to the required 1.2.189).

Hello, I encounter the same problem, I execute `sudo apt-get install libvulkan1` and it shows `1.1.70+dfsg1-1ubuntu0.18.04.1` is the latest version. How did you upgrade the `libvulkan` or do you know how to upgrade it on Ubuntu 18.04? 

Looking forward to your reply! Thank you!
