### ISSUE TITLE
Loading mtl files for PartNet-Mobility dataset with Kuafu Renderer

### ISSUE THREAD

**Issue by akshaygadipatil** [haosulab/SAPIEN#91]
Hi Fanbo @fbxiang,

I am interested in learning how to load the material files from partnet-mobility dataset and render them with the 3D model.

I looked up the `kuafu_mat.py` script, but it creates its own materials. What is the exact command to load `.mtl` file using the initialized renderer?

**Comment by akshaygadipatil** [comment]
Also, I see that `visual_body.type` is not implemented for Kuafu Renderer.
Below is the output when I do this using Kuafu:

`Traceback (most recent call last):
  File "render_sapien_kuafu_cam_pos.py", line 194, in <module>
    mesh = get_mesh_for_obj(obj)
  File "../mesh_utils.py", line 84, in get_mesh_for_obj
    print(visual_body.type)
RuntimeError: getType is not implemented`

FYI, the function is available for Vulkan renderer, and I was able to successfully render articulated 3D models. 

How do I make use of this functionality with Kuafu renderer? @fbxiang 
Thanks.

**Comment by fbxiang** [comment]
.mtl files are loaded in Kuafu automatically. You just need to load the .obj file.
Kuafu is also only designed to work as a renderer. Many convenient functions such as querying object properties (e.g. type) are not implemented as this point. For now, please use KuafuRenderer only for ray-traced rendering and use the default VulkanRenderer if you need more functionalities.

**Comment by akshaygadipatil** [comment]
Thanks. The rendering quality from VulkanRenderer, in my case, are poor. 

I am attaching a few images below, where you can see that the rendering of one partnet-mobility model is basically just color info. 
Important image information such as edges, especially on the articulated parts, are not captured using Vulkan.

Is there a way to improve the rendering quality using Vulkan?

![image](https://user-images.githubusercontent.com/22264995/191634739-6f509757-566c-4596-8abe-f834aa4864c0.png)
![image](https://user-images.githubusercontent.com/22264995/191634770-b39f607b-1212-4234-99eb-cf20e973392d.png)
![image](https://user-images.githubusercontent.com/22264995/191634807-0e5e5784-cb6f-4567-acde-782b2668af5a.png)

**Comment by fbxiang** [comment]
The default VulkanRenderer is based on rasterization, getting it to look nice is more like an art. Typically adding some lights and  an environment map help it to look better to humans (many algorithms may or may not care since it is not fully physical either way). 
The KuafuRenderer (which is also implemented with Vulkan) is based on physically correct ray tracing, it is much slower but gives more photorealistic images with less effort.
You can debug your code with the default VulkanRenderer, and do a final rendering with KuafuRenderer.

**Comment by fbxiang** [comment]
Now sapien 2.2.0 is released and Kuafu is deprecated.
The original VulkanRenderer is now renamed  SapienRenderer and it supports all functionalities of Kuafu.
SapienRenderer's ray tracing is very slightly faster than Kuafu but a lot more stable.
You can now switch between rasterization and ray tracing without changing the renderer.
