### ISSUE TITLE
Kuafu interupted when importing extreme complex geometry

### ISSUE THREAD

**Issue by ray8828** [haosulab/SAPIEN#92]
Hi, thanks for sharing this great work, when using kuafu render, loading an extremely complex (>1000 cvx collision mes) urdf gives my an error, which works fine for the vanilla rasterization rendering, could you provide some way to maybe increase the buffer setting? Thanks!
<img width="840" alt="image" src="https://user-images.githubusercontent.com/26106300/191659513-673b3879-0732-4759-aa0a-952b6b7ce1c4.png">

**Comment by jetd1** [comment]
Hi, you can set these parameters accordingly in KuafuConfig when you create the render. See the api doc here: https://sapien.ucsd.edu/docs/latest/apidoc/sapien.core.html#sapien.core.pysapien.KuafuConfig
